fail_fast: true
repos:
  - repo: local
    hooks:
      - id: format
        name: Run cargo format
        entry: cargo +nightly fmt --check
        language: system
        pass_filenames: false
        stages: [commit, push, manual]
      - id: clippy
        name: Run cargo clippy
        entry: cargo clippy --no-deps --all-targets
        language: system
        pass_filenames: false
        stages: [commit, push, manual]
      - id: nextest
        name: Run cargo nextest
        entry: cargo nextest run --fail-fast
        language: system
        pass_filenames: false
        stages: [push, manual]
      - id: doc
        name: Run cargo doc
        entry: bash -c 'env RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps --document-private-items'
        language: system
        pass_filenames: false
        stages: [push, manual]
      - id: build
        name: Check WASM compilation
        entry: cargo +nightly check --target=wasm32-unknown-unknown --workspace --no-default-features
        language: system
        pass_filenames: false
        stages: [push, manual]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
