@startuml
skinparam responseMessageBelowArrow true
'autoactivate on
!theme mars

participant "Client" as client
participant "Vamm" as vamm
database "Storage" as svamm

client -> vamm++: Get settlement price request
vamm -[#green]> svamm++: Get vamm
svamm --> vamm--: vamm
vamm -> vamm: Sanity checks
vamm -> vamm: Compute settlement price
vamm --> client--: Return call result
@enduml
