@startuml remove_margin
!theme mars

actor "Trader" as user
participant "Clearing\nHouse" as ch
database "Collateral" as accs
database "Positions" as positions
database "Markets" as mkts
participant "vAMM/\nOracle" as price
collections "Collateral\naccount" as vault

user -> ch : ""remove_margin""

== Validity checks ==

ch -> ch ++: ""risk_free_collateral""
    ch -[#green]> accs : get margin
    ch -[#green]> positions : get all user positions
    ch -[#green]> mkts : get all markets invested
    ch -[#green]> price : get prices
return free collateral

ch -> ch: ensure requested amount <\nfree collateral

== Storage updates ==

ch -[#red]> accs : reduce collateral by requested amount

== Asset transfers ==

group return collateral
ch -> vault : transfer to caller's ""AccountId""
vault -> user : collateral
end

====

?<-o ch : emit event
@enduml
